common/head_tag.html, settings.yml
This commit adds the ability for the user to choose to display the search banner below the header, or above the main content. This is needed for themes using multiple components in these plugin outlets.
=> Add ability for user to choose outlet

javascripts/discourse/components/search-banner.js
Had a report of an error here: https://meta.discourse.org/t/search-banner-theme-component/122939/37?u=awesomerobot
updating `currentUser` to `this.currentUser` fixed it
=> fix currentUser not found error

javascripts/discourse/api-initializers/init-search-banner.js
No longer needed since it's removed in core
See https://github.com/discourse/discourse/pull/14788
=> FIX: Remove `clickOutside` event

javascripts/discourse/api-initializers/init-search-banner.js
It's not ideal, but we have to reimplement core's logging here so search result clicks are correctly logged both when searching in the header and when searching in the second instance of the widget added by this component.
=> FEATURE: Log search result clicks

common/common.scss, javascripts/discourse/api-initializers/init-search-banner.js
This changes `search-term` widget's ID for the input so that we do not
include two elements with the same ID in the DOM.
=> DEV: Do not reuse core's element ID for the input

common/common.scss, javascripts/discourse/api-initializers/init-search-banner.js
The search button doesn't do anything at the moment, so this makes it click through to the full search page. 
Originally reported here: https://meta.discourse.org/t/search-banner/122939/99?u=awesomerobot
=> UX: let search button click through to full search

common/common.scss, javascripts/discourse/api-initializers/init-search-banner.js, locales/en.yml
This adds an optional translation, default empty, so admins can add text to the search button like so:
=> UX: add optional search button text

javascripts/discourse/api-initializers/init-search-banner.js
See https://github.com/discourse/discourse/pull/23867
We are moving from "I18n" to "discourse-i18n"
=> DEV: Use new i18n package

common/common.scss
This PR fixes overlapping icons to the right of the input. I adjusted the search icon to appear to the left, following most site standards.
**Before**
**After**
=> UX: Style adjustments and fixes

javascripts/discourse/api-initializers/init-search-banner.js
Raised in https://meta.discourse.org/t/search-banner/122939/109?u=isaac
> a dark overlay comes over the entire site page and i’m unable to navigate the site
Force the search menu to always render as a dropdown and don't apply the `slide out` styling (dark overlay).
https://github.com/discourse/discourse-search-banner/assets/50783505/17a5009b-d0c5-40c8-95a5-b00a0685970c
https://github.com/discourse/discourse-search-banner/assets/50783505/4962728f-759b-41bc-af49-6bdc5fe209f7
=> FIX: Force search menu to always be displayed as a dropdown

javascripts/discourse/components/search-banner.js
When a non-US locale is the site's default, and the user chooses a US locale, the button would render the fallback key when no translation is set: 
Before:
After:
So I've added a check for the default key, which should be considered false. 
Originally reported here: https://meta.discourse.org/t/bug-with-search-banner-search-button-text-shown-in-search-banner-theme-component/273628
I think this is because the translation is being used in an unexpected way as a pseudo-setting (i.e., if it's empty, don't render the button)
=> FIX: don't use fallback key as button text

common/common.scss, mobile/mobile.scss
This fixes the clear and advanced search icon centering, and removes some dead CSS
This was an alignment fix for mobile that's no longer necessary (and causes a slight misalignment)
```scss
.custom-search-banner-wrap .search-icon {
top: 0.15em;
}
```
This is done in the core search component
```scss
.searching a.show-advanced-search {
display: none;
}
```
These css selectors are not siblings, so the CSS is never applied 
```scss
// hide the search icon when a search context is selected
// eg when searching in a topic
.search-input .search-context + .search-icon:not(.has-search-button-text),
.search-input .search-context ~ .search-icon:not(.has-search-button-text) {
display: none;
}
```
The parent element is no longer flex, so this isn't applied
```scss
.search-input {
flex: 1 1 auto;
} …
```
=> UX: fix button alignment, remove dead CSS

common/common.scss
These styles get a little complex and weren't working properly in RTL locales... 
Before:
After: 
No changes in LTR:
=> UX: fix alignment for RTL languages

spec/system/viewing_search_banner_spec.rb
We are moving this component into core here
https://github.com/discourse/discourse/pull/31516
When that is merged, we can re-enable these specs
hidden behind the core site setting
=> DEV: Disable system specs for now

about.json, common/common.scss, locales/en.yml, spec/system/viewing_search_banner_spec.rb, test/acceptance/search-banner-test.js
Since we are moving a simplified version of this
into core at https://github.com/discourse/discourse/pull/31516,
this component becomes Advanced Search Banner.
The core welcome banner will be hidden if this
component is installed.
This commit also re-enables previously disabled
specs that would have failed the core PR.
=> DEV: Update theme name to Advanced Search Banner

.discourse-compatibility, common/common.scss, javascripts/discourse/components/search-banner.hbs, mobile/mobile.scss, spec/system/viewing_search_banner_spec.rb, test/acceptance/search-banner-test.js
Relies on https://github.com/discourse/discourse/pull/32099 from
core, which introduces a searchInputId to differentiate
search inputs, since we have 3 now (welcome banner, header, icon)
=> FIX: Use search input id for <SearchMenu /> component

common/common.scss, javascripts/discourse/components/search-banner.hbs, stylesheets/special-styles.scss
This PR makes some adjustments to the component due to merging the search banner into core. We will now rely as much as possible on the core stylesheet & classes.
=> DEV: Refactor

common/common.scss, javascripts/discourse/components/search-banner.hbs
This PR adds the wrap class back into the theme in order to un-break themes relying on it.
=> UX: Add wrap class back

common/common.scss
Some core styles seem to be hiding this when they shouldn't be... will have to investigate, but this fixes for now
Before: 
After:
=> UX: show search input on narrow screens

test/acceptance/search-banner-test.js
With https://github.com/discourse/discourse/pull/33098,
you can no longer see the search button in the header if
the welcome/search banner is shown, so we don't need to
check for this.
=> DEV: Remove qunit test for search input

common/common.scss
The paragraph below the welcome headline was left-aligned, causing a visual inconsistency with the rest of the centered content. This change applies `text-align: center` to the paragraph to fix the layout. 
Ref. https://meta.discourse.org/t/-/374631
=> FIX: Center paragraph text

common/common.scss
This variable was changed in core and broke the entire padding declaration, better to just avoid that. 
Before: 
After:
=> FIX: restore padding broken due to missing variable
